config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    resources :users do
      resources :photos
    end
    # get 'photos/index'
    # get 'photos/show'
  end
  get 'admins/top' => 'admins/users#top', as:'top_admins_path'
  # namespace :admins do
  #   resources :albums do
  #     resources :photos
  #   end
  # end

  # get 'notices/link_through'
	devise_for :admins, controllers: {
  	sessions: 		 'admins/sessions',
  	passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 		 'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

resources :users do
    resources :cameras, only: [:index, :show]
    resources :events
    resources :photos
    resource :follows, only: [:create, :destroy]
    resources :albums do
      resources :my_photos
    end
end

  resources :my_events, only: [:new, :index, :show, :edit, :destroy] do
    resources :albums, only: [:new, :index, :show, :edit, :destroy] do
      resources :photos
    end
  end
    resources :events do
      resources :albums do
        resources :photos
      end
    end


  resources :album_items


resources :photos do
  resource :likes, only: [:create, :destroy]
  resources :post_comments, only: [:create, :destroy]
end
resources :my_albums
  # get 'my_albums/new' => 'my_albums#new', as:'new_my_album'

get 'users/top' => 'users#top'
post 'my_albums/:album_id/photo/:id/add_photo' => 'my_albums#add_album_item', as: 'add_my_album_item'
delete 'my_albums/:album_id/photo/:id/del_photo' => 'my_albums#del_album_item', as: 'del_my_album_item'
get 'users/:id/welcome' => 'users#welcome', as: 'welcome_user'
get 'users/:user_id/photos/:id/pre' => 'photos#pre_photo', as: 'photo_pre'
get 'users/:user_id/photos/:id/next' => 'photos#next_photo', as: 'photo_next'
get 'notices/:id/follow_back' => 'notices#follow_back', as: 'follow_back'
get 'notices/:id/link_through' => 'notices#link_through', as: 'link_through'
post 'users/search' => 'users#search', as: 'user_search'
resources :categories, only: [:index]

root 'users#top'
  # get 'events/new'
  # get 'events/index'
  # get 'events/show'
  # get 'events/edit'

# resource :my_album_items
  # get 'my_albums/:id/add_photo' => 'my_albums#add_album_item', as: 'add_my_album_item'
  # get 'my_albums/new'
  # get 'my_albums/index'
  # get 'my_albums/show'
  # get 'my_albums/edit'

  # get 'my_album_items/new'
  # get 'my_album_items/index'
  # get 'my_album_items/edit'

  # get 'albums/index'
  # get 'albums/show'

  # get 'my_photos/new'
  # get 'my_photos/index'
  # get 'my_photos/show'
  # get 'my_photos/edit'
# resources :photos do
	# resources :categories, only: [:index]
# end

  # get 'photos/index'
  # get 'photos/show'

  # get 'categories/index'

# get 'my_events/index'
#   get 'my_events/new'
#   get 'my_events/show'
#   get 'my_events/edit'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notice.rb
class Notice < ApplicationRecord
	belongs_to :notice_by, class_name: 'User'
	belongs_to :user
	belongs_to :photo
	belongs_to :follow, optional: true
	belongs_to :like, optional: true
	belongs_to :post_comment, optional: true
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController

	after_action :check_follow, only: [:link_through]

		def index
			@notices = current_user.notices
		end

		def link_through
			@notice = Notice.find(params[:id])
			if @notice.update(read: true)
				if @notice.notice_type == "コメント" || @notice.notice_type == "いいね！"
					redirect_to user_photo_path(@notice.user_id, @notice.photo_id)
				elsif @notice.notice_type == "フォロー"
					puts "bbb"
					redirect_to user_path(@notice.notice_by)
				end
			else
				puts "aaa"
			end
		end

	private

		def check_follow #通知からユーザーをフォローバックした場合のアクション
			return if @notice.notice_type == "コメント" || @notice.notice_type == "いいね！"
				# @give_user = current_user
				# @get_user = @notice.notice_by
					# @notice.update(read: true)
				current_user.follow(@notice.notice_by)
		end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_notice.html.erb
<% notices.reverse.each do |notice| %>
	<div class="notice-list">
		<% if notice.read == false && notice.notice_type == "コメント" || notice.notice_type == "いいね！" %>
			<div style="display:flex;justify-content: space-between;">
				<div style="margin: auto 5px;">
					<%= link_to user_path(notice.notice_by), style: "color:black;" do %>
						<b><%= notice.notice_by.nickname %>さん</b>
					<% end %>
					があなたの投稿に「 <b><%= notice.notice_type %></b> 」しました！</div>
				<%= link_to link_through_path(notice) do %>
					<%= attachment_image_tag notice.photo, :image, :fill, 100, 100, style: "width:40px; height:40px;object-fit:cover;" %>
				<% end %>
			</div>
			<%#= link_to "確認する", link_through_path(notice), class: "ui mini inverted purple button"%>
		<% elsif notice.read == false && notice.notice_type == "フォロー" %>
			<div style="display:flex;justify-content: space-between;">
				<%= link_to user_path(notice.notice_by) do %>
					<%= attachment_image_tag notice.notice_by, :thumbnail, fallback: 'user_preset_image.png', style: "width:40px; height:40px;object-fit:cover;border-radius:50%;"%>
				<% end %>
				<div style="margin: auto 10px;"><b><%= notice.notice_by.nickname %>さん</b>があなたを <b><%= notice.notice_type %></b> しました！</div>
				<% unless current_user.following? notice.notice_by %>
					<%= link_to link_through_path(notice) do %>
						<div class="ui inverted violet mini button">フォローバック</div>
					<% end %>
				<% else %>
					<%= link_to link_through_path(notice) do %>
						<div class="ui inverted secondary mini button">確認</div>
					<% end %>
				<% end %>
			</div>
		<% else %>
		<% end %>
	</div>
<% end %>

app/views/notices/_notice_info.html.erb
<div>
	<% if current_user.notices.where(read: false).count > 0 %>
		<%= render 'notices/notice', notices: current_user.notices.where(read: false) %>
	<% else %>
		<p style="padding:20px;"><font color="gray">現在お知らせはありません</font></p>
	<% end %>
</div>

app/views/notices/link_through.html.erb
<h1>Notices#link_through</h1>
<p>Find me in app/views/notices/link_through.html.erb</p>