config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    resources :users do
      resources :photos
    end
    # get 'photos/index'
    # get 'photos/show'
  end
  get 'admins/top' => 'admins/users#top', as:'top_admins_path'
  # namespace :admins do
  #   resources :albums do
  #     resources :photos
  #   end
  # end

  # get 'notices/link_through'
	devise_for :admins, controllers: {
  	sessions: 		 'admins/sessions',
  	passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 		 'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

resources :users do
    resources :cameras, only: [:index, :show]
    resources :events
    resources :photos
    resource :follows, only: [:create, :destroy]
    resources :albums do
      resources :my_photos
    end
end

  resources :my_events, only: [:new, :index, :show, :edit, :destroy] do
    resources :albums, only: [:new, :index, :show, :edit, :destroy] do
      resources :photos
    end
  end
    resources :events do
      resources :albums do
        resources :photos
      end
    end


  resources :album_items


resources :photos do
  resource :likes, only: [:create, :destroy]
  resources :post_comments, only: [:create, :destroy]
end
resources :my_albums
  # get 'my_albums/new' => 'my_albums#new', as:'new_my_album'

get 'users/top' => 'users#top'
post 'my_albums/:album_id/photo/:id/add_photo' => 'my_albums#add_album_item', as: 'add_my_album_item'
delete 'my_albums/:album_id/photo/:id/del_photo' => 'my_albums#del_album_item', as: 'del_my_album_item'
get 'users/:id/welcome' => 'users#welcome', as: 'welcome_user'
get 'users/:user_id/photos/:id/pre' => 'photos#pre_photo', as: 'photo_pre'
get 'users/:user_id/photos/:id/next' => 'photos#next_photo', as: 'photo_next'
get 'notices/:id/follow_back' => 'notices#follow_back', as: 'follow_back'
get 'notices/:id/link_through' => 'notices#link_through', as: 'link_through'
post 'users/search' => 'users#search', as: 'user_search'
resources :categories, only: [:index]

root 'users#top'
  # get 'events/new'
  # get 'events/index'
  # get 'events/show'
  # get 'events/edit'

# resource :my_album_items
  # get 'my_albums/:id/add_photo' => 'my_albums#add_album_item', as: 'add_my_album_item'
  # get 'my_albums/new'
  # get 'my_albums/index'
  # get 'my_albums/show'
  # get 'my_albums/edit'

  # get 'my_album_items/new'
  # get 'my_album_items/index'
  # get 'my_album_items/edit'

  # get 'albums/index'
  # get 'albums/show'

  # get 'my_photos/new'
  # get 'my_photos/index'
  # get 'my_photos/show'
  # get 'my_photos/edit'
# resources :photos do
	# resources :categories, only: [:index]
# end

  # get 'photos/index'
  # get 'photos/show'

  # get 'categories/index'

# get 'my_events/index'
#   get 'my_events/new'
#   get 'my_events/show'
#   get 'my_events/edit'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
# ------------------検索-----------------------------------------------------------

  def self.search(search) #self.でクラスメソッドとしている
     if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      User.where(['name LIKE ?', "%#{search}%"])
    else
      # User.all
    end
  end

# -------------------------------------------------------------------------------
  attachment :thumbnail
  attachment :header_image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable


  has_many :photos
  has_many :likes, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :notices, dependent: :destroy

  has_and_belongs_to_many :cameras

  acts_as_followable # フォロワー機能
  acts_as_follower   # フォロー機能


# varidetes-----------------------------------

	validates :first_name,
  		presence: true,
  		length: { minimum: 1, maximum: 10}

  validates :last_name,
  		presence: true,
  		length: { minimum: 1, maximum: 10}

  validates :nickname,
  		presence: true,
  		uniqueness: true,
  		length: { in: 2..10 }

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

	def top
		
	end

	def index
		@user = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		user.update(user_params)
	end

	def destroy
		user = User.find(params[:id])
		user.destroy
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    welcome_user_path(current_user)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
    session[:album_id] = nil
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:top]
  before_action :sign_in_required, only: [:show, :welcome]
  # protect_from_forgery except: :search

	def top
	end

  def welcome
    @photo = Photo.new
  end

  def index
    @user = current_user
    @photo = Photo.new
    # @rand_photo = Photo.order("RANDOM()").first
    # @photos = Photo.all.order(created_at: :desc)
    @photos = Photo.page params[:page]
  end

  def search
    @user = current_user
    @result = User.find_by('nickname LIKE ?', "%#{params[:search]}%")
    if @result == nil
      redirect_back(fallback_location: user_path(current_user))
    else
      redirect_to user_path(@result.id)
    end
  end

  def show
      @photo = Photo.new
    # if User.exists?(id: params[:id])
      @user = User.find(params[:id])
      @photos = @user.photos.order(created_at: :desc)
      # @like_hash = Like.where(user_id: current_user.id ).pluck(:id, :photo_id).size
      @likes_count = Photo.where(user_id: @user.id).pluck(:like_count).sum
    # else
    # end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
    # redirect_back fallback_location: { controller: 'users', action: 'show' }
    redirect_to user_path(user)
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :nickname, :email, :header_image, :thumbnail)
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<%= render partial: 'layouts/user_edit_modal' %>

app/views/users/_followed_by_index.html.erb
<% if current_user.followers_count == 0 %>
	<div class="item">
		<font color="gray"><div align="center">フォロワーはいません</div></font>
	</div>
<% else %>
	<% current_user.followers.reverse.each do |follower| %>
			<%= link_to user_path(follower), class: "item filter-drop-shadow", style: "display:flex; justify-content:flex-start;" do%>
				<%= attachment_image_tag follower, :thumbnail, fallback: 'user_preset_image.png', class: "sub-header-dropdown-user-icon" %>
				<%= follower.nickname %>
				<!-- <span><font size="2" color="gray"><%#= follower.created_at.strftime('%-m月%-d日') %></font></span> -->
			<% end %>
	<% end %>
<% end %>

app/views/users/_follower_index.html.erb
<% if current_user.follow_count == 0 %>
	<div class="item">
		<div>
			フォロワーはいません
		</div>
	</div>
<% else %>
	<% current_user.all_following.reverse.each do |follower| %>
		<%# binding.pry %>
			<%= link_to user_path(follower), class: "item filter-drop-shadow", style: "display:flex; justify-content:flex-start;" do%>
				<%= attachment_image_tag follower, :thumbnail, fallback: 'user_preset_image.png', class: "sub-header-dropdown-user-icon" %>
				<%= follower.nickname %>
				<!-- <span><font size="2" color="gray"><%#= follower.created_at.strftime('%-m月%-d日') %></font></span> -->
			<% end %>
	<% end %>
<% end %>

app/views/users/_index.html.erb
<div class="photo-contents-box">
	<% @photos.each do |photo| %>
		<div class="content-box">
			<div class="photo-box">
				<div class="img">
					<%= link_to user_photo_path( photo.user, photo ), style: "display:inline-block;
						position:absolute;
						top: 0;
						left: 0;
						width:100%;
						height:100%;" do
					%>
						<%= attachment_image_tag photo, :image, :fill, 800, 600, :style => "border-radius:5px; width:400px;height:300px;"%>
						<div class="overlay-fillter">
							<div class="post-user-box2">
								<%= link_to user_path(photo.user) do %>
									<%= attachment_image_tag photo.user, :thumbnail, fallback: 'user_preset_image.png', :size => "40x40", class: "photo-box-user-icon" %>
								<% end %>
								<div class="img-summ"><%= photo.title %>
									<% if photo.user == current_user %>
										<p class="postphoto-user-name" style="font-size: 13px;">あなた</p>
									<% else %>
										<p class="postphoto-user-name" style="font-size: 13px;">by <%= photo.user.nickname %></p>
									<% end %>
									<div class="comments-count">
										<span><font size="3"><%= photo.post_comments.count if photo.post_comments.count > 0 %></font></span>
										<%= link_to user_photo_path(photo.user, photo) do %>
											<i class="far fa-comment fa-2x" style="color:rgba(255, 255, 255, 0.8);"></i>
										<% end %>
									</div>
									<div class="like-box">
										<%= render 'likes/likes', photo: photo %>
									</div>
								</div>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	<% end %><!-- each end -->
</div>
<%#= paginate @photos %>
<script>

	$(function() {

		$('.img').hover(
			function() {
				$(this).find($('.overlay-fillter')).stop().fadeIn(200);
				//マウスカーソルが重なった時の処理
			},
			function() {
				//マウスカーソルが離れた時の処理
				$(this).find($('.overlay-fillter')).stop().fadeOut(200);
			}
		);

	});


</script>

app/views/users/_my_activity.html.erb
<% if Notice.where(notice_by: current_user).count == 0 %>
	<div class="item">
		<div class="list">
			<font color="gray">アクティビティはありません</font>
		</div>
	</div>
<% else %>
	<% Notice.where(notice_by: current_user).reverse.each do |notice| %>
		<% if notice.notice_type == "コメント" || notice.notice_type == "いいね！" %>

			<%= link_to user_photo_path(notice.user_id, notice.photo), class: "item" do %>
				<div class="list" style="display:flex; justify-content: space-between;">
					<div style="margin:auto 0;">
						<b><%= notice.user.nickname %></b>さんの投稿に「<b><%= notice.notice_type %></b>」しました
					</div>
					<%= attachment_image_tag notice.photo, :image, style: "margin-left:3px; width:40px; height:40px; object-fit:cover;" %>
				</div>
			<% end %><!-- link_to end -->

		<% else %>

			<%= link_to user_path(notice.user), class: "item" do %>
				<div class="list" style="display:flex; justify-content: space-between;">
					<div style="margin: auto 0;">
						<b><%= notice.user.nickname %></b>さんを「<b><%= notice.notice_type %></b>」しました
					</div>
					<%= attachment_image_tag notice.user, :thumbnail, style: "margin-left:3px; width:40px; height:40px; object-fit:cover; border-radius:50%;" %>
				</div>
			<% end %>

		<% end %><!-- if end -->
	<% end %><!-- each end -->
<% end %>

app/views/users/_save.js.erb
$(".profile-edit-button").html("<%= escape_javascript(render 'index') %>")
$(".ui.modal").modal("hide")

app/views/users/edit.html.erb
<div class="main-box">
  <div class="devise-main-box2">
    <div class="devise-contents-box">
      <div class="registration-input-box" style="">
      <h2 align="center">プロフィール編集</h2>
        <%#= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
        <%= form_for(@user) do |f| %>
          <%= devise_error_messages! %>
          <div class="username-box">
            <div class="field">
              <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", :placeholder => "姓", class: "devise-form-control devise-form-style" %>
            </div>
            <div class="field">
              <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", :placeholder => "名", class: "devise-form-control devise-form-style", style: "margin-left: 5px;" %>
            </div>
          </div>
          <div class="nickname-box">
            <%= f.label :nickname, "ニックネーム（２文字以上１０文字以下）" %>
            <%= f.text_field :nickname, autofocus: true, :placeholder => "ニックネーム（２文字以上１０文字以下）", class: "devise-form-control devise-form-style", minlength: 2, maxlength: 10 %>
          </div>
            <div class="field">
              <%= f.label :email %>
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "devise-form-control devise-form-style", placeholder: "totte@gmail.com" %>
            </div>

            <!-- <div class="field" style="padding-top: 20px;">
            <%= f.label :パスワード変更 %><br/>
            <%= f.password_field :current_password, autocomplete: "current-password", class: "devise-form-control devise-form-style", placeholder: "現在のパスワード" %>
            </div>

            <div class="field">
              <#% if @minimum_password_length %>
              <em><%#= @minimum_password_length %></em>
              <#% end %>
              <#%= f.password_field :password, autocomplete: "off", class: "devise-form-control devise-form-style", placeholder: "新しいパスワード(" + @minimum_password_length.to_s + "ケタ以上)" %>
            </div>

            <div class="field">
              <%#= f.password_field :password_confirmation, autocomplete: "off", class: "devise-form-control devise-form-style", placeholder: "パスワード確認" %>
            </div> -->

            <div class="actions">
              <%= link_to :back, class: "ui secondary floated inverted tiny button" do %>
              <p>戻る</p>
              <% end %>
              <button type="submit" class="ui blue right floated button">変更を保存</button>
            </div>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/users/edit.js.erb
$("#profile-edit-button").html("<%= escape_javascript(render 'edit') %>")
$(".ui.modal").modal("show")

app/views/users/index.html.erb
<title>HOME全ユーザー写真投稿一覧</title>
<div class="main-box" style="position:relative;">
	<div class="main-visual">
		<%#= attachment_image_tag @rand_photo, :image, class: "main-visual" %>
		<img id="t-m-v" src="/header-image.jpg" class="header-image">
	</div>
		<%= render 'layouts/sub_header', photo: @photo %>
		<h2 align="center">All User Photos</h2>
		<div class ="index">
			<%= render 'index', photos: @photos %>
		</div>
		<div style="padding-bottom:50px;" align="center">
			<%= link_to_next_page @photos, "more", remote: true, id: "more_link", class: "ui inverted secondary button" %>
		</div>
</div>


<script>


	$(function() {
		$('#t-m-v').fadeIn(2000);
		// $('#index').click(function(){
		// 	$('#more_link').fadeIn(1000);
		// });

		$('.img').hover(
			function() {
				$(this).find($('.overlay-fillter')).stop().fadeIn(200);
				//マウスカーソルが重なった時の処理
			},
			function() {
				//マウスカーソルが離れた時の処理
				$(this).find($('.overlay-fillter')).stop().fadeOut(200);
			}
		);

	});


</script>

app/views/users/index.js.erb
$('.index').append("<%= escape_javascript(render 'index', object: @photos) %>");
$("#more_link").replaceWith("<%= escape_javascript( link_to_next_page @photos, 'more', remote: true, id: 'more_link', class: 'ui inverted secondary button' ) %>");

app/views/users/results.html.erb
<div class="main-box">
	<%= render 'layouts/sub_header', photo: @photo %>
</div>

app/views/users/show.html.erb
<title>Users#show</title>
<section>
	<div class="main-box">
		<% if @photos.blank? %>
			<%= render 'layouts/user_main_visual', user: @user%>
			<%= render 'layouts/sub_header', photo: @photo %>
			<h2 align="center">My Photos</h2>
			<div class="main-contents-box">
				<div style= "padding:150px;text-align:center;">
					<font size="6" color="gray">No Photo</font>
				</div>
			</div>
		<% else %>
			<%= render 'layouts/user_main_visual', user: @user%>
			<%= render 'layouts/sub_header', photo: @photo%>
			<% if @user == current_user %>
				<h2 align="center">My Photos</h2>
			<% else %>
				<h2 align="center">Photos</h2>
			<% end %>
			<div class="main-contents-box" style="display:flex; justify-content:space-around;">
				<div class="my-photos-box" style="padding-bottom: 80px;">
					<!-- each start -->
					<% @photos.each do |photo| %>
						<div class="my-photo-img">
							<%= link_to user_photo_path(photo.user, photo),  class: "user-show-photo-box" do%>
								<%= attachment_image_tag photo, :image, :fill, 600, 400, style: "width:100%; height:100%;" %>
								<%#= attachment_image_tag photo, :image, :style => "width:100%; height:100%;", fomat:"jpg" %>
								<div class="overlay-fillter-radius-none">
									<div class="post-user-box">
										<p class="photo-title"><%= photo.title %></p>
										<div class="comments-count" style="display:flex;">
											<span><font size="3" color="white"><%= photo.post_comments.count if photo.post_comments.count > 0 %></font></span>
											<%= link_to user_photo_path(photo.user, photo) do %>
												<i class="far fa-comment fa-2x" style="color:rgba(255, 255, 255, 0.8);"></i>
											<% end %>
										</div>
										<!-- いいねAjax -->
										<div class="like-box">
											<%= render 'likes/likes', photo: photo %>
										</div>
										<!-- いいねAjax end -->
									</div>
									<% if photo.user == current_user %>
										<div class="trushbox-icon" style="width:50px;height:50px;">
											<%= link_to user_photo_path(photo.user, photo), method: :delete, data: { confirm: '削除します。よろしいですか？' }, class: "overlay-trashbox-icon" do %>
												<i class="far fa-trash-alt fa-2x" style="color: rgba(255, 255, 255, 0.7);"></i>
											<% end %>
										</div>
									<% end %><!-- if end -->
								</div>
							<% end %><!-- link_to end -->
						</div>
					<% end %><!-- each end -->
				</div>
			</div>
		<% end %>
	</div>
</section>

<script>
$(function() {

	$('.my-photo-img').hover(
		function() {
			//マウスカーソルが重なった時の処理
			$(this).find($('.overlay-fillter-radius-none')).stop().fadeIn(200);
		},
		function() {
		//マウスカーソルが離れた時の処理
			$(this).find($('.overlay-fillter-radius-none')).stop().fadeOut(200);
		}
	);

});

$('.activating.element')
  .popup()
;


$('.trushbox-icon')
  .popup({
    inline: true
  })
;

</script>

app/views/users/top.html.erb
<div class="top-bg">
	<div class="contents-box">
		<p class="catch-copy">写真で繋がるSNS</p>
		<div style=";padding-top:120px;margin: 0 auto;" align="center">
			<img src="/assets/totte-logo.png" style="width:250px;">
		</div>
		<div class="buttons" style="margin-top:30px;">
			<%= link_to new_user_registration_path do %>
				<div type="" class="entrance-button">新規登録</div>
			<% end %>
			<%= link_to new_user_session_path do %>
				<div type="" class="entrance-button">サインイン</div>
			<% end %>
		</div>

		<div class="sns-icons-box">
			<a style="color:white;" href="https://www.facebook.com/share.php?url=<%= request.url %>" rel="nofollow" target="_blank">
				<i class="fab fa-facebook-square fa-4x"></i>
			</a>

			<a style="color:white;" href="https://twitter.com/share?url=<%= request.url %>&text=写真で繋がるSNS totte" rel="nofollow" target="_blank">
				<i class="fab fa-twitter-square fa-4x"></i>
			</a>

			<a style="color:white;" href="http://line.me/R/msg/text/?http://totte.biz" rel="nofollow" target="_blank">
				<i class="fab fa-line fa-4x"></i>
			</a>
		</div>
	</div>
</div>

app/views/users/welcome.html.erb
<div class="first-contact-box" style="display:none;">
		<img src="/album-header13.jpg" alt="" style="width: 100%;
													width: 100%;
    												height: 700px;
    												object-fit: cover;">
			<div class="overlay-box">
				<div class="lets-massage-box" style="display:none;">
					<p align="center"><font size="7">Hallo, totte!</font></p>
					<div align="center"><font size="5">さあ、はじめよう</font></div>
					<div class="lets-massage">
						<p style="font-size:18px; text-align:center;">
							<% if Date.today.strftime('%-H') >= 5.to_s && Date.today.strftime('%-H') <= 18.to_s %>
								こんにちは！ <%= current_user.nickname %>さん
							<% else %>
								こんばんは！ <%= current_user.nickname %>さん
							<% end %>
						</p>
						<p style="font-size:15px;">
							はじめまして。	ようこそtotteへ！<br>
							世界中の人が <%= current_user.nickname %>さんの撮った作品を心待ちにしているでしょう。<br>
							<%= current_user.nickname %>さんの何気ない１枚も、素敵な作品の１枚です。<br>
							まずは下のボタンから写真をアップロードしてみましょう。<br>
						</p>
					</div>
					<div style="text-align: center;">
						<button id="post-photo-modal" class="ui inverted purple button">写真を投稿する</button>
						<div style="margin-top:15px;">
							<%= link_to user_path(current_user) do %>
								<div class="ui button">あとで投稿する</div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>


		<div id="modal" class="ui mini modal" style="padding-bottom:10px;">
			<div class="header" align="center">写真投稿</div>
				<i class="close icon"></i>
				<div class="content">
			  			<%= form_for @photo, url: photos_path do |f| %>
						<%= f.attachment_field :image, style: "" %>
						<div class="ui form" style="margin: 10px auto;">
							<%= f.label :title, "写真のタイトル" %>
							<%= f.text_field :title, placeholder: "タイトル", class: "field"%>
						</div>
							<button type="submit" class="ui purple mini button">投稿</button>
						<% end %>
				<div class="actions">
					<button class="ui deny right floated button">戻る</button>
				</div>
		  	</div>
		</div>


<script>

	$('#post-photo-modal').click(function() {
		  $('#modal')
  			.modal('show');
	});

	$('.first-contact-box').fadeIn(1500);

    setTimeout(function(){
    	$('.lets-massage-box').fadeIn(1000);
    },1500);

</script>