config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    resources :users do
      resources :photos
    end
    # get 'photos/index'
    # get 'photos/show'
  end
  get 'admins/top' => 'admins/users#top', as:'top_admins_path'
  # namespace :admins do
  #   resources :albums do
  #     resources :photos
  #   end
  # end

  # get 'notices/link_through'
	devise_for :admins, controllers: {
  	sessions: 		 'admins/sessions',
  	passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 		 'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

resources :users do
    resources :cameras, only: [:index, :show]
    resources :events
    resources :photos
    resource :follows, only: [:create, :destroy]
    resources :albums do
      resources :my_photos
    end
end

  resources :my_events, only: [:new, :index, :show, :edit, :destroy] do
    resources :albums, only: [:new, :index, :show, :edit, :destroy] do
      resources :photos
    end
  end
    resources :events do
      resources :albums do
        resources :photos
      end
    end


  resources :album_items


resources :photos do
  resource :likes, only: [:create, :destroy]
  resources :post_comments, only: [:create, :destroy]
end
resources :my_albums
  # get 'my_albums/new' => 'my_albums#new', as:'new_my_album'

get 'users/top' => 'users#top'
post 'my_albums/:album_id/photo/:id/add_photo' => 'my_albums#add_album_item', as: 'add_my_album_item'
delete 'my_albums/:album_id/photo/:id/del_photo' => 'my_albums#del_album_item', as: 'del_my_album_item'
get 'users/:id/welcome' => 'users#welcome', as: 'welcome_user'
get 'users/:user_id/photos/:id/pre' => 'photos#pre_photo', as: 'photo_pre'
get 'users/:user_id/photos/:id/next' => 'photos#next_photo', as: 'photo_next'
get 'notices/:id/follow_back' => 'notices#follow_back', as: 'follow_back'
get 'notices/:id/link_through' => 'notices#link_through', as: 'link_through'
post 'users/search' => 'users#search', as: 'user_search'
resources :categories, only: [:index]

root 'users#top'
  # get 'events/new'
  # get 'events/index'
  # get 'events/show'
  # get 'events/edit'

# resource :my_album_items
  # get 'my_albums/:id/add_photo' => 'my_albums#add_album_item', as: 'add_my_album_item'
  # get 'my_albums/new'
  # get 'my_albums/index'
  # get 'my_albums/show'
  # get 'my_albums/edit'

  # get 'my_album_items/new'
  # get 'my_album_items/index'
  # get 'my_album_items/edit'

  # get 'albums/index'
  # get 'albums/show'

  # get 'my_photos/new'
  # get 'my_photos/index'
  # get 'my_photos/show'
  # get 'my_photos/edit'
# resources :photos do
	# resources :categories, only: [:index]
# end

  # get 'photos/index'
  # get 'photos/show'

  # get 'categories/index'

# get 'my_events/index'
#   get 'my_events/new'
#   get 'my_events/show'
#   get 'my_events/edit'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/my_albums_controller.rb
class MyAlbumsController < ApplicationController
  before_action :authenticate_user!

  def index
    @photo = Photo.new
    # @user = current_user
    @albums = Album.all.reverse_order
  end

  def new
    if session[:photo] == nil
      session[:photo] = []
    end
    @photo = Photo.new
    # @num = params[:num].to_i
    @num = 0
    @album = current_album
    # @count = session[:photo].count
    @count = current_album.album_items.count
    @user = current_user
    @photos = @user.photos.reverse_order
      # puts session[:photo]
    # @album_items = @album.album_items
  end

# 作成中のアルバムに写真を追加
  def add_album_item
    @album = current_album
    if @album.blank?
      redirect_to user_path(current_user)
    else
      @album_item = AlbumItem.new
      @photo = Photo.find(params[:id])
      # @album_items = @album.album_items.find_by(photo_id: @photo.id)
      if @album_items.blank?
        @album_item.photo_id = @photo.id
        @album_item.album_id = current_album.id
        if @album_item.save
          session[:photo].push(@album_item.photo_id)
          session[:photo] = session[:photo].sort_by{ |u| u }.reverse
          redirect_to new_my_album_path
        else
          redirect_to new_my_album_path
        end
      else
        redirect_to user_path(current_user)
      end
    end
  end

  # 作成中のアルバムから写真を削除
  def del_album_item
    @photo = Photo.find(params[:id])
    @album = current_album
    @album_item = @album.album_items.find_by(photo_id: @photo.id)
    if @album_item.destroy
      session[:photo].delete(@album_item.photo_id)
      redirect_to new_my_album_path
    end
  end


  def create
    @album = current_album
    @album_items = @album.album_items

    if @album.save
      session[:album_id] = nil
      session[:photo] = nil
      redirect_to user_albums_path(current_user)
    else
      p "保存できていません"
      redirect_to user_albums_path(current_user)
    end
  end

  def show
    if Album.exists?
      @user = current_user
      @album = Album.find(params[:id])
      @album_items = @album.album_items
    else
    end
  end

  def edit
    @user = current_user
    @album = @user.album
  end

  def update
    @album = current_album
    if @album.update(album_params)
      session[:album_id] = nil
      session[:photo] = nil
      redirect_to user_albums_path(current_user)
    else
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album_items = @album.album_items
    if @album.destroy
      redirect_to user_albums_path(current_user)
    end
  end


  private

  def album_params
    params.require(:album).permit(:title, :introduction, :thumbnail_id, :user_id, :event_id, :like_count,
                                                                                album_items_attributes:[[:id,
                                                                                                        :albumm_id,
                                                                                                        :photo_id,
                                                                                                        :_destroy]])
  end

  def album_item_params
    params.require(:album_item).permit(:album_id, :photo_id)
  end
end

app/helpers/my_albums_helper.rb
module MyAlbumsHelper
end

app/views/my_albums/add_album_item.js.erb
$("#album_item_<%= @photo.id %>").html("<%= j(render partial: 'my_albums/album_item', locals: { photo: @photo, photos: @photos, num: @num }) %>")
$("#button").html("<%= j(render partial: 'my_albums/button', locals: { count: @count, album: @album }) %>")

app/views/my_albums/del_album_item.js.erb
$("#album_item_<%= @photo.id %>").html("<%= j(render partial: 'my_albums/album_item', locals: { photo: @photo, photos: @photos, num: @num }) %>")
$("#button").html("<%= j(render partial: 'my_albums/button', locals: { count: @count, album: @album }) %>")

app/views/my_albums/edit.html.erb
<h1>MyAlbums#edit</h1>
<p>Find me in app/views/my_albums/edit.html.erb</p>

app/views/my_albums/index.html.erb
<title>Album Index</title>
<div class="main-box">
	<div class="main-visual">
		<img id="a-m-v" src="album-header99.jpg" class="header-image">
	</div>
	<%= render 'layouts/sub_header', photo: @photo %>
	<h2 align="center">All User Albums</h2>
	<div class="photo-contents-box" style="padding-bottom:100px;">
	<% if @albums.blank? || @albums.count == 1 && session[:album_id] != nil %>
		<div class="">
			<font size="6" color="gray">No Albums</font>
		</div>
	<% else %>
		<div class="ui special cards" style="justify-content: center;">
			<% @albums.each do |album| %>
				<% if album.album_items.count == 0 %>
				<% else %>
					<div class="card" style="margin:15px;filter: drop-shadow(3px 3px 5px gray);">
						<div class="blurring dimmable image">
							<div class="ui dimmer">
								<div class="content">
									<div class="center">
										<%= link_to user_album_path(album.user, album) do %>
										<div class="ui inverted violet button" style="filter:drop-shadow(3px 3px 1px gray);">詳細を見る</div>
										<% end %>
									</div>
								</div>
							</div>
							<!-- <img src="album-header7.jpg"> -->
							<%= attachment_image_tag album.album_items.first.photo, :image, style: "position:relative;" %>
						</div>
						<div class="content">
							<div>
								<%= link_to user_path(album.user) do %>
								<%= attachment_image_tag album.user, :thumbnail, fallback: 'user_preset_image.png', style: "width:40px;height:40px;object-fit:cover;", class: "ui avatar user-icon-background" %>
								<% end %>
								<span class="header" style="font-size:15px;"><%= album.title %></span>
							</div>
							<div class="meta">
								<div class="date" align="right"><%= album.created_at.strftime('%Y年%-m月%-d日') %>に作成</div>
								<div align="right">by <%= album.user.nickname %></div>
							</div>
						</div>
						<div class="extra content" style="display:flex;justify-content: space-between;">
							<div>
								<i class="large images outline icon"></i><%= album.album_items.count %>枚
							</div>
						</div>
					</div>
				<% end %>
			<% end %><!-- each end -->
		</div>
	<% end %>
	</div><!-- content-box end -->
</div>
<!-- ------------------------------------- -->
<script>
$(function() {
	$('.img').hover(
		function() {
			$(this).find($('.overlay-fillter')).fadeIn(200);
			//マウスカーソルが重なった時の処理
		},
		function() {
		//マウスカーソルが離れた時の処理
			$(this).find($('.overlay-fillter')).fadeOut(200);
		}
	);
});


$('.ui.sticky')
  .sticky({
    context: '#example1'
  });


$('.special.cards .image').dimmer({
  on: 'hover'
});


$('#a-m-v').fadeIn(2000);

</script>

app/views/my_albums/new.html.erb
<title>新規アルバム投稿</title>
<div class="main-box" style="padding-bottom: 110px;">
	<%= render 'layouts/sub_header', photo: @photo %>
	<div class="main-contents-box" style="padding:10px 0 100px 0;">
		<h2 align="center">アルバム作成</h2>
		<p align= "center" >アルバムにしたい写真を選んでください</p>
		<div id="button" style="margin-bottom: 5px;">
			<%#= render 'button', count: @count, album: @album %>
			<% if @count == 0 %>
				<div class="ui form" align="center">
					<div class="field" style="width: 50%;">
						<div style="margin-bottom:10px;" align="center">選択中の写真　<%= @count %>枚</div>
						<%= form_for @album, url: my_album_path(current_album), id: "button", method: :patch do |f| %>
							<div align="left"><%= f.label :title, "アルバムのタイトル(写真を選択すると入力できるようになります)" %></div>
							<%= f.text_field :title, disabled: true, placeholder: "アルバムのタイトルを入力", style: "margin-bottom:5px;" %>
							<%= f.submit "写真を選択して下さい", class: "ui inverted violet disabled fluid button" %>
						<% end %>
					</div>
				</div>
			<% else %>
				<div class="ui form" align="center">
					<div class="field" style="width: 50%;">
						<div style="margin-bottom:10px;" align="center">選択中の写真　<%= @count %>枚</div>
						<%= form_for @album, url: my_album_path(current_album), id: "button", method: :patch do |f| %>
							<div align="left"><%= f.label :title, "アルバムのタイトル" %></div>
							<%= f.text_field :title, placeholder: "アルバムのタイトルを入力", style: "margin-bottom:5px;" %>
							<%= f.submit "アルバム作成", class: "ui violet fluid button" %>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
		<% if @photos.blank? %>
			<div style= "padding:120px;text-align:center;">
				<font size="6" color="gray">No Photo</font>
			</div>
		<% else %>
			<div class="album-item-index-box">
				<% @photos.reverse.each do |photo| %>
					<%#= render 'album_item', photo: photo, num: @num %>
					<% if session[:photo][@num] == photo.id %>
						<!-- 選択中の画像の表示 -->
						<% session[:photo][@num] %>
						<% @num %>
						<% @num = @num + 1 %>
						<div class="selected-filter">
							<%= attachment_image_tag photo, :image, :fill, 400, 400, style: "width:100%; height:100%; object-fit:cover;" %>
							<div class="filter-overlay">
								<%= link_to del_my_album_item_path(current_album, photo), data: { no_turbolink: true }, method: :delete, class: "overlay-trashbox-icon" do %>
									<i class="far fa-trash-alt fa-2x" style="color: rgba(255, 255, 255, 0.7);"></i>
								<% end %>
							</div>
						</div>
						<% next %>
					<% end %>
					<%= link_to add_my_album_item_path(current_album, photo), data: { no_turbolink: true }, method: :post do %>
						<div><%= attachment_image_tag photo, :image, :fill, 400, 400, class: "your-photos-mini" %></div>
					<% end %>
				<% end %><!-- end @photos.reverse.each -->
			</div>
		<% end %><!-- end @photos.blank? -->
	</div>
</div>

<script>
	$(function() {
		$('.img').hover(
			function() {
				$(this).find($('.overlay-fillter')).fadeIn(200);
				//マウスカーソルが重なった時の処理
			},
			function() {
			//マウスカーソルが離れた時の処理
				$(this).find($('.overlay-fillter')).fadeOut(200);
			}
		);

	});
</script>

app/views/my_albums/test_new.html.erb
<title>新規アルバム投稿</title>

<div class="main-box">
	<div class="main-visual2">
	</div>
	<%= render 'layouts/sub_header' %>
	<div class="main-contents-box">
		<h2>Item List</h2><%#= binding.pry %>
		<% if current_album.album_items.blank? %>
		  <button class="ui inverted violet button disabled">Create Album</button>
		<% else %>
		  <%= link_to my_albums_path, method: :post do %>
			  <button class="ui inverted violet button">Create Album</button>
		  <% end %>
		<% end %>
		<div style="display:flex; flex-direction:row; justify-content:flex-start; flex-wrap: wrap;">
			<% @photos.each do |photo| %>
				<%= link_to add_my_album_item_path(photo), method: :post do %>
					<div class="">
						<%= attachment_image_tag photo, :image, class: "your-photos-mini" %>
					</div>
				<% end %>
			<% end %>
		</div>
		<% @album_items.each do |album_item| %>
			<%= attachment_image_tag album_item.photo, :image, class: "your-photos-mini" %>
		<% end %>
	</div>
</div>


<script>
	
</script>